
[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port 8000"
restartPolicyType = "ON_FAILURE"

[phases.setup]
aptPkgs = ["libgobject-2.0-0", "libcairo2", "libpango-1.0-0", "libpangocairo-1.0-0", "libgdk-pixbuf2.0-0", "shared-mime-info"]